server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/WuIsGoing/springcloud-config.git
#          searchPaths: respo
          username: 410035082@qq.com
          password: boy3773223
      label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
