eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: service-zuul
server:
  port: 8130
spring:
  application:
    name: service-zuul

zuul:
  ignored-services: service-feign
  routes:
    api-feign:
      path: /api-feign/**
      serviceId: service-feign

