#feign:
#  hystrix:
#    enabled: true
spring:
  application:
    name: security-order
  freemarker:
    cache: false
    settings:
      template_update_delay: 0
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/demo
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 9000
