eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8130
spring:
  application:
    name: service-zuul

zuul:
  routes:
    api-feign:
      path: /api-feign/**
      serviceId: service-feign
